insert into public.drugs (id, generic, strength, unit, percent, form, route, release, brand, had, preg, renal) values
(1, 'Abacavir', '300', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(2, 'Abacavir + Lamivudine', '600 + 300', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(4, 'Acetylcysteine', '200', 'mg', null, 'sachet', 'oral', null, null, false, 'B', false),
(5, 'Acetylcysteine', '300', 'mg/3 mL', null, 'amp', 'IV', null, null, false, 'B', false),
(7, 'Activated charcoal', '5', 'g', null, 'sachet', 'oral', null, null, false, null, false),
(10, 'Acyclovir', '400', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(11, 'Acyclovir', '500', 'mg', null, 'vial', 'IV', null, null, false, 'B', true),
(12, 'Adenosine', '6', 'mg/2 mL', null, 'amp', 'IV', null, null, true, 'C', false),
(13, 'Albendazole', '200', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(17, 'Alfacalcidol (Vitamin D3)', '0.25', 'mcg', null, 'tab', 'oral', null, null, false, 'C', false),
(18, 'Alfuzosin hydrochloride', '10', 'mg', null, 'tab', 'oral', 'ER', null, false, null, false),
(19, 'Allopurinol', '100', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(21, 'Aluminium hydroxide + Magnesium hydroxide + Simethicone', '960 + 330 + 60', 'mg/15 mL', null, 'gel', 'topical', null, 'Alum milk', false, 'C', false),
(22, 'Ambroxol', '30', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(23, 'Amikacin', '500', 'mg/2 mL', null, 'vial', 'IV', null, null, false, 'D', true),
(24, 'Amiloride + Hydrochlorothiazide', '5 + 50', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(27, 'Amiodarone', '150', 'mg/3 mL', null, 'amp', 'IV', null, null, true, 'D', false),
(28, 'Amiodarone', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(29, 'Amitriptyline', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(30, 'Amitriptyline', '25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(32, 'Amlodipine', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(35, 'Amoxicillin', '125', 'mg/5 mL', null, 'syrup', 'oral', null, null, false, 'B', false),
(36, 'Amoxicillin', '250', 'mg', null, 'cap', 'oral', null, null, false, 'B', false),
(37, 'Amoxicillin', '500', 'mg', null, 'cap', 'oral', null, null, false, 'B', false),
(39, 'Amoxicillin + Clavulanic acid', '1 + 0.2', 'g', null, 'injection', 'IV', null, 'Augmentin', false, null, false),
(40, 'Amoxicillin + Clavulanic acid', '400 + 57', 'mg/5 mL', null, 'syrup', 'oral', null, 'Augmentin', false, null, false),
(41, 'Amoxicillin + Clavulanic acid', '500 + 125', 'mg', null, 'tab', 'oral', null, 'Augmentin', false, null, true),
(42, 'Amoxicillin + Clavulanic acid', '875 + 125', 'mg', null, 'tab', 'oral', null, 'Augmentin', false, 'B', false),
(43, 'Amphotericin B deoxycholate', '50', 'mg', null, 'vial', 'IV', null, null, false, 'B', true),
(44, 'Ampicillin', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', false),
(45, 'Ampicillin', '250', 'mg', null, 'vial', 'IV', null, null, false, 'B', false),
(46, 'Ampicillin', '500', 'mg', null, 'vial', 'IV', null, null, false, 'B', true),
(47, 'Ampicillin + Sulbactam', '2 + 1', 'g', null, 'vial', 'IV', null, null, false, 'B', true),
(48, 'Antazoline + Tetrahydrozoline', '50 + 40', 'mg/100 mL', null, 'eye drops', 'ophthalmic', null, 'Hista-oph', false, null, false),
(49, 'Aripiprazole', '400', 'mg', null, 'injection', 'IV', 'ER', null, false, null, false),
(50, 'Artesunate', '60', 'mg/1 mL', null, 'powder', 'oral', null, null, false, null, false),
(51, 'Ascorbic acid (Vitamin C)', '100', 'mg', null, 'sachet', 'oral', null, null, false, 'A', false),
(52, 'Aspirin', '81', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(53, 'Aspirin', '300', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(54, 'Atenolol', '50', 'mg', null, 'tab', 'oral', null, null, false, 'D', true),
(57, 'Atorvastatin', '40', 'mg', null, 'tab', 'oral', null, null, false, 'X', false),
(58, 'Atropine sulfate', '0.6', 'mg/1 mL', null, 'amp', 'IV', null, null, true, 'C', false),
(59, 'Baclofen', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(61, 'Penicillin G Benzathine', '1.2', 'MU', null, 'vial', 'IM', null, null, false, 'B', false),
(62, 'Benzhexol', '2', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(63, 'Benzhexol', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(64, 'Benzocaine + Hydrocortisone Acetate + Zinc oxide', '40 + 7.5 + 250', 'mg', null, 'suppository', 'rectal', null, 'Doproct', false, 'A', false),
(65, 'Podophyllin', '25', 'g/100 mL', '25', 'solution', null, null, null, false, null, false),
(66, 'Benzyl benzoate', '25', 'g/100 mL', '25', 'emulsion', 'topical', null, null, false, null, false),
(67, 'Betahistine mesilate', '6', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(71, 'Bisacodyl', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(72, 'Bisoprolol', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(73, 'Bromhexine', '8', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(74, 'Bromocryptine', '2.5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(75, 'Budesonide', '200', 'mcg/dose', null, 'MDI', 'inhaled', null, null, false, 'B', false),
(76, 'Budesonide + Formoterol', '160 + 4.5', 'mcg/1 dose', null, 'turbuhaler', 'inhaled', null, 'Symbicort', false, null, false),
(78, 'Ergotamine tartrate + Caffeine', '1 + 100', 'mg', null, 'tab', 'oral', null, null, false, 'X', false),
(79, 'Calamine + Zinc oxide', '15 + 5', 'g/100 mL', null, 'lotion', 'topical', null, null, false, null, false),
(81, 'Calcium carbonate', '1500', 'mg', null, 'tab', 'oral', null, null, false, 'A', false),
(82, 'Calcium gluconate', '0.45', 'meq/1 mL', null, 'amp', 'IV', null, null, true, 'C', false),
(83, 'Calcium polystyrene sulfonate', '5', 'g', null, 'sachet', 'oral', null, 'Kalimate', false, 'C', false),
(84, 'Methyl salicylate', '12.5', 'g/100 g', '12.5', 'cream', 'topical', null, null, false, null, false),
(85, 'Capecitabine', '500', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(86, 'Captopril', '25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(87, 'Carvedilol', '6.25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(88, 'Carvedilol', '12.5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(89, 'Cefazolin', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', false),
(90, 'Cefdinir', '100', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(91, 'Cefixime', '100', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(92, 'Cefotaxime', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', false),
(93, 'Ceftazidime', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', true),
(94, 'Ceftriaxone', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', false),
(95, 'Cetirizine', '5', 'mg/5 mL', null, 'syrup', 'oral', null, null, false, 'B', false),
(96, 'Chlorhexidine gluconate', '120', 'mg/100 mL', '0.12', 'solution', 'topical', null, null, false, null, false),
(98, 'Chloramphenicol', '50', 'mg/10 mL', null, 'drops', 'topical', null, null, false, 'C', false),
(99, 'Chlordiazepoxide', '5', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(101, 'Chloroquine', '250', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(102, 'Chlorpheniramine', '2', 'mg/5 mL', null, 'syrup', 'oral', null, null, false, 'B', false),
(103, 'Chlorpheniramine', '4', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(104, 'Chlorpheniramine', '10', 'mg/mL', null, 'injection', 'IV', null, null, false, 'B', false),
(105, 'Chlorpromazine', '25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(106, 'Chlorpromazine', '50', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(107, 'Chlorpromazine', '100', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(108, 'Chlortetracycline', '10', 'mg/1 g', '1', 'ointment', 'topical', null, null, false, 'D', false),
(110, 'Cinnarizine', '25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(111, 'Ciprofloxacin', '200', 'mg/100 mL', null, 'injection', 'IV', null, null, false, 'C', true),
(113, 'Ciprofloxacin', '500', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(114, 'Clarithromycin', '500', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(116, 'Clindamycin', '300', 'mg', null, 'cap', 'oral', null, null, false, 'B', false),
(117, 'Clindamycin', '600', 'mg/4 mL', null, 'vial', 'IV', null, null, false, 'B', false),
(118, 'Clobetasol propionate', '50', 'mg/100 g', '0.05', 'cream', 'topical', null, null, false, 'C', false),
(119, 'Clofazimine', '100', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(120, 'Clonazepam', '0.5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(121, 'Clonazepam', '2', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(122, 'Clopidogrel', '75', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(123, 'Clotrimazole', '1', 'g/100 g', '1', 'cream', 'topical', null, null, false, 'B', false),
(124, 'Clotrimazole vaginal', '100', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(125, 'Cloxacillin', '1', 'g', null, 'vial', 'IV', null, null, false, 'B', false),
(127, 'Clozapine', '25', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(128, 'Clozapine', '100', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(129, 'Colchicine', '0.6', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(130, 'Colistin', '150', 'mg', null, 'vial', 'IV', null, null, false, 'C', false),
(132, 'Conjugated estrogens', '625', 'mcg', null, 'tab', 'oral', null, 'Premarin', false, 'X', false),
(133, 'Cyanocobalamin (Vitamin B12)', '1', 'mg/1 mL', null, 'injection', 'IV', null, null, false, null, false),
(134, 'Vitamin B complex', '100 + 5 + 0.005', 'mg', null, 'tab', 'oral', null, null, false, 'A', false),
(135, 'Cyclophosphamide', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(136, 'Cyproheptadine', '4', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(137, 'Dapsone', '100', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(138, 'Deferiprone', '500', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(140, 'Dexamethasone', '4', 'mg/mL', null, 'injection', 'IV', null, null, false, 'C', false),
(141, 'Dextromethorphan', '15', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(142, 'Diazepam', '2', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(143, 'Diazepam', '5', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(144, 'Diazepam', '10', 'mg/2mL', null, 'injection', 'IV', null, null, false, 'D', false),
(145, 'Diclofenac', '25', 'mg/3ml', null, 'injection', 'IV', null, null, false, 'B', false),
(146, 'Dicloxacillin', '62.5', 'mg/5ml', null, 'syrup', 'oral', null, null, false, 'B', false),
(147, 'Dicloxacillin', '125', 'mg/5ml', null, 'syrup', 'oral', null, null, false, 'B', false),
(148, 'Dicloxacillin', '250', 'mg', null, 'cap', 'oral', null, null, false, 'B', false),
(149, 'Dicloxacillin', '500', 'mg', null, 'cap', 'oral', null, null, false, 'B', false),
(150, 'Dicyclomine', '10', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(153, 'Digoxin', '0.25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(154, 'Digoxin', '0.25', 'mg/mL', null, 'injection', 'IV', null, null, true, 'C', false),
(156, 'Dimenhydrinate', '50', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(157, 'Dimenhydrinate', '50', 'mg/mL', null, 'injection', 'IV', null, null, false, 'B', false),
(158, 'Diosmin + Hesperidin', '450 + 50', 'mg', null, 'tab', 'oral', null, 'Daflon', false, null, false),
(159, 'Dipotassium clorazepate', '5', 'mg', null, 'cap', 'oral', null, null, false, 'D', false),
(160, 'Dolutegravir', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(161, 'Domperidone', '5', 'mg/5ml', null, 'suspension', 'oral', null, null, false, null, false),
(162, 'Domperidone', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(163, 'Donepezil', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(164, 'Dopamine', '250', 'mg/10mL', null, 'injection', 'IV', null, null, true, 'C', false),
(165, 'Doxazosin', '2', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(166, 'Doxycycline', '100', 'mg', null, 'cap', 'oral', null, null, false, 'D', false),
(167, 'Efavirenz', '200', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(168, 'Efavirenz', '600', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(169, 'Enalapril', '5', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(170, 'Enalapril', '20', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(171, 'Enoxaparin', '40', 'mg/0.4ml', null, 'prefilled syringe', 'SC', null, null, false, 'B', true),
(172, 'Enoxaparin', '60', 'mg/0.6ml', null, 'prefilled syringe', 'SC', null, null, false, 'B', true),
(173, 'Entacapone', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(174, 'Epinephrine', '1', 'mg/1 mL', null, 'amp', 'IV', null, null, true, 'C', false),
(175, 'Epinephrine + Lidocaine', '1.25 + 2', 'mg/100 mL + g/100 mL', null, 'injection', 'IV', null, null, false, 'B', false),
(176, 'Epoetin alfa', null, null, null, null, null, null, null, false, null, false),
(177, 'Ertapenem', '1', 'g', null, 'injection', 'IV', null, null, false, null, true),
(178, 'Erythromycin estolate', '125', 'mg/5ml', null, 'syrup', 'oral', null, null, false, 'X', false),
(180, 'Ethambutol', '400', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(181, 'Ethambutol', '500', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(182, 'Isoniazid + Rifampicin + Pyrazinamide + Ethambutol', '75 + 150 + 400 + 275', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(183, 'Ethinylestradiol + Levonorgestrel (ยาคุม)', '30 + 150', 'mcg', null, 'tab', 'oral', null, 'Pill', false, 'X', false),
(185, 'Etonogestrel', '68', 'mg', null, 'implant', null, null, null, false, null, false),
(186, 'Etoposide', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(187, 'Famotidine', '20', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(188, 'Favipiravir', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(189, 'Fenofibrate', '100', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(190, 'Fenoterol + Ipratropium', '31.25 + 12.5', 'mg/100 mL', null, 'nebule', 'inhaled', null, 'Berodual', false, 'B', false),
(191, 'Fenoterol + Ipratropium', '31.25 + 12.5', 'mg/100 mL', null, 'solution', null, null, 'Berodual', false, 'B', false),
(192, 'Fenoterol + Ipratropium', '50 + 20', 'mcg/1 dose', null, 'MDI', 'inhaled', null, 'Berodual', false, 'B', false),
(193, 'Fentanyl', '25', 'mcg', null, 'patch', 'transdermal', null, null, false, null, false),
(194, 'Fentanyl', '50', 'mcg', null, 'patch', 'transdermal', null, null, false, null, false),
(195, 'Ferrous fumarate', '45', 'mg/0.6ml', null, 'suspension', 'oral', null, null, false, null, false),
(196, 'Ferrous fumarate', '200', 'mg', null, 'tab', 'oral', null, null, false, 'A', false),
(197, 'Ferrous fumarate + Folic acid + Potassium iodide', '185 + 0.4 + 0.196', 'mg', null, 'tab', 'oral', null, 'Triferdine', false, null, false),
(198, 'Filgrastim', '300', 'mcg/1 mL', null, 'prefilled syringe', 'IV', null, null, false, null, false),
(199, 'Fluconazole', '200', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(200, 'Flunarizine', '5', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(201, 'Fluoxetine', '20', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(202, 'Fluphenazine decanoate', '25', 'mg/mL', null, 'amp', 'IM', 'ER', null, false, 'C', false),
(203, 'Fluticasone furoate', '27.5', 'mcg/1 dose', null, 'spray', 'nasal', null, 'Avamys', false, null, false),
(204, 'Salmeterol + Fluticasone propionate', '25 + 125', 'mcg/1 dose', null, 'powder', 'MDI', null, 'Seretide Evohaler', false, null, false),
(206, 'Folic acid', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(207, 'Formaldehyde', '37', 'g/100 mL', null, 'solution', null, null, null, false, null, false),
(208, 'Furosemide', '20', 'mg/2ml', null, 'injection', 'IV', null, 'Lasix', false, 'C', false),
(209, 'Furosemide', '40', 'mg', null, 'tab', 'oral', null, 'Lasix', false, 'C', false),
(210, 'Furosemide', '250', 'mg/25ml', null, 'injection', 'IV', null, 'Lasix', false, 'C', false),
(211, 'Furosemide', '500', 'mg', null, 'tab', 'oral', null, 'Lasix', false, 'C', false),
(212, 'Gabapentin', '100', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(213, 'Gabapentin', '300', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(215, 'Gemfibrozil', '300', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(216, 'Gentamicin', '80', 'mg/2 mL', null, 'injection', 'IV', null, null, false, 'C', false),
(218, 'Glipizide', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(506, 'ORS adoult (Oral Rehydration Salt)', '8', 'oz', null, 'powder', 'oral', null, null, false, null, false),
(219, 'ORS baby (Oral Rehydration Salt)', '4', 'oz', null, 'powder', 'oral', null, null, false, null, false),
(221, 'Gramicidin + Neomycin sulfate + Polymyxin b sulfate', '25 + 2 + 5000', 'mcg/1 mL + mg/1 mL + IU/1 mL', null, 'eye drops', 'ophthalmic', null, 'Poly-oph', false, 'C', false),
(222, 'Griseofulvin', '500', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(223, 'Guaifenesin', '100', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(224, 'Guaifenesin', '100', 'mg/5ml', null, 'syrup', 'oral', null, null, false, null, false),
(225, 'Haloperidol', '2', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(226, 'Haloperidol', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(227, 'Haloperidol', '5', 'mg/mL', null, 'injection', 'IV', null, null, false, 'C', false),
(228, 'Haloperidol decanoate', '50', 'mg/mL', null, 'injection', 'IM', 'ER', null, false, null, false),
(229, 'Heparin sodium', '5000', 'unit', null, 'injection', 'IV', null, null, false, null, false),
(230, 'Heparin sodium', '25000', 'IU/5ml', null, 'injection', 'IV', null, null, false, null, false),
(231, 'Hepatitis B vaccine (immunoglobulin)', '180', 'IU/1 mL', null, 'amp', 'IV', null, null, false, null, false),
(233, 'Hydralazine', '20', 'mg', null, 'amp', 'IV', null, null, true, null, false),
(234, 'Hydralazine', '25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(235, 'Hydralazine', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(236, 'Hydrochlorothiazide (HCTZ)', '25', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(237, 'Hydrocortisone sodium succinate', '100', 'mg', null, 'vial', 'IV', null, null, false, 'C', false),
(239, 'Hydroxycarbamide (hydroxyurea)', '500', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(240, 'Hydroxychloroquine', '200', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(241, 'Hydroxyzine', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(242, 'Hyoscine', '5', 'mg/5ml', null, 'syrup', 'oral', null, 'Buscopan', false, null, false),
(244, 'Hyoscine', '20', 'mg/mL', null, 'injection', 'IV', null, 'Buscopan', false, 'C', false),
(245, 'Ibuprofen', '100', 'mg/5ml', null, 'syrup', 'oral', null, null, false, null, false),
(246, 'Ibuprofen', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(247, 'Ibuprofen', '400', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(249, 'Indinavir', '400', 'mg', null, 'cap', 'oral', null, 'Inavir', false, 'C', false),
(250, 'Indomethacin', '25', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(251, 'Insulin regular (RI)', '100', 'IU/1 mL', null, 'vial', 'SC', null, null, false, 'B', false),
(255, 'Isoniazid', '50', 'mg/1mL', null, 'solution', 'oral', null, null, false, null, false),
(256, 'Isoniazid', '100', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(257, 'Isoniazid + Rifampicin', '75 + 150', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(258, 'Isoniazid + Rifapentine', '300 + 300', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(259, 'Isophane insulin (NPH)', '100', 'IU/1 mL', null, 'vial', 'SC', null, null, false, 'B', false),
(260, 'Isophane insulin (NPH) + Insulin regular (RI)', '70 + 30', 'IU/1 mL', null, 'prefilled pen', 'SC', null, null, false, 'B', false),
(261, 'Isophane insulin (NPH) + Insulin regular (RI)', '70 + 30', 'IU/1 mL', null, 'vial', 'SC', null, null, false, 'B', false),
(263, 'Isosorbide dinitrate (อมใต้ลิ้น)', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(264, 'Isosorbide mononitrate', '20', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(267, 'Ketoconazole shampoo', '2', 'g/100 mL', null, 'solution', 'topical', null, null, false, null, false),
(268, 'Lactulose', '66.7', 'g/100 mL', null, 'solution', 'oral', null, null, false, 'B', false),
(269, 'Lamivudine', '10', 'mg/mL', null, 'syrup', 'oral', null, null, false, null, false),
(270, 'Lamivudine', '100', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(271, 'Lamivudine', '150', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(272, 'Lamivudine', '300', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(273, 'Lamivudine + Nevirapine + Stavudine', '150 + 200 + 30', 'mg', null, 'tab', 'oral', null, 'GPO-VIR S30', false, null, false),
(274, 'Lamivudine + Nevirapine + Zidovudine', '150 + 200 + 250', 'mg', null, 'tab', 'oral', null, 'GPO-VIR Z250', false, null, false),
(275, 'Lamivudine + Stavudine', '150 + 30', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(276, 'Lamivudine + Zidovudine', '150 + 300', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(277, 'Lamotrigine', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(278, 'Lercanidipine', '20', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(280, 'Levetiracetam', '500', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(281, 'Levodopa + Benserazide', '100 + 25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(282, 'Levodopa + Benserazide', '200 + 50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(283, 'Levodopa + Carbidopa', '250 + 25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(284, 'Levofloxacin', '500', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(285, 'Levonorgestrel (ยาคุมฉุกเฉิน)', '1.5', 'mg', null, 'tab', 'oral', null, null, false, 'X', false),
(286, 'Levonorgestrel', '75', 'mg', null, 'implant', null, null, null, false, null, false),
(287, 'Levothyroxine sodium', '0.1', 'mg', null, 'tab', 'oral', null, null, false, 'A', false),
(289, 'Lidocaine', '20', 'mg/mL', '2', 'solution', 'topical', null, 'Viscous®', false, 'B', false),
(293, 'Lithium carbonate', '300', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(294, 'Loperamide', '2', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(295, 'Lopinavir + Ritonavir', '200 + 50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(296, 'Loratadine', '10', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(297, 'Lorazepam', '0.5', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(298, 'Lorazepam', '1', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(299, 'Lorazepam', '2', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(300, 'Losartan', '50', 'mg', null, 'tab', 'oral', null, null, false, 'D', true),
(302, 'Magnesium hydroxide', '1.2', 'g/15 mL', null, 'suspension', 'oral', null, null, false, 'B', false),
(303, 'Magnesium sulfate', '100', 'mg/1 mL', '10', 'injection', 'IV', null, null, false, 'B', false),
(304, 'Magnesium sulfate', '500', 'mg/1 mL', '50', 'injection', 'IV', null, null, false, 'B', false),
(305, 'Manidipine', '20', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(306, 'Mebendazole', '100', 'mg/5ml', null, 'suspension', 'oral', null, null, false, 'C', false),
(507, 'Medroxyprogesterone acetate', '10', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(307, 'Depot Medroxyprogesterone acetate (DMPA)', '150', 'mg/3 mL', null, 'injection', 'IM', null, null, false, 'D', false),
(308, 'Mefenamic acid', '250', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(309, 'Meloxicam', '7.5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(310, 'Meropenem', '1', 'g', null, 'vial', 'IV', null, null, false, null, true),
(311, 'Metformin', '500', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(313, 'Methimazole', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(314, 'Methotrexate', '2.5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(315, 'Methyldopa', '250', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(316, 'Methylergometrine maleate', '0.2', 'mg/1 mL', null, 'amp', 'IV', null, 'Methergine', false, 'C', false),
(317, 'Methylphenidate', '10', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(318, 'Metoclopramide', '10', 'mg/2mL', null, 'injection', 'IV', null, null, false, 'B', false),
(319, 'Metoprolol tartrate', '100', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(320, 'Metronidazole', '200', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(321, 'Metronidazole', '500', 'mg/100mL', null, 'injection', 'IV', null, null, false, 'B', false),
(322, 'Midazolam', '5', 'mg/mL', null, 'injection', 'IV', null, null, false, null, false),
(323, 'Misoprostol', '200', 'mcg', null, 'tab', 'oral', null, null, false, null, false),
(324, 'Molnupiravir', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(325, 'Morphine sulfate (MST)', '10', 'mg', null, 'tab', 'oral', 'ER', null, false, null, false),
(326, 'Morphine sulfate', '10', 'mg/5mL', null, 'syrup', 'oral', null, null, false, null, false),
(327, 'Morphine sulfate', '10', 'mg/mL', null, 'injection', 'IV', null, null, false, null, false),
(328, 'Morphine sulfate', '20', 'mg', null, 'cap', 'oral', 'ER', 'Kapanol', false, null, false),
(329, 'Morphine sulfate (MST)', '30', 'mg', null, 'tab', 'oral', 'ER', null, false, null, false),
(330, 'Moxifloxacin', '400', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(331, 'Multivitamin', null, null, null, 'syrup', 'oral', null, null, false, 'A', false),
(332, 'Multivitamins', null, null, null, 'tab', 'oral', null, null, false, null, false),
(333, 'Mupirocin', '2', 'g/1 g', '2', 'ointment', 'topical', null, null, false, null, false),
(334, 'Mycophenolate mofetil', '250', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(336, 'Naproxen', '250', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(337, 'Nevirapine', '50', 'mg/5 mL', null, 'suspension', 'oral', null, null, false, 'C', false),
(338, 'Nevirapine', '200', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(339, 'Nicardipine', '10', 'mg/10 mL', null, 'injection', 'IV', null, null, true, null, false),
(342, 'Vitamin B complex (B1 + B2 + B3 + B6)', '100 + 0.5 + 100 + 1', 'mg/1 mL', null, 'injection', 'IV', null, null, false, 'A', false),
(343, 'Nicotinic acid (Vitamin B3)(Niacin)', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(344, 'Nifedipine', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(346, 'Nitroglycerin', '50', 'mg/10ml', null, 'injection', 'IV', null, null, true, null, false),
(347, 'Norepinephrin', '4', 'mg/4ml', null, 'injection', 'IV', null, null, true, null, false),
(348, 'Norethisterone', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(349, 'Norfloxacin', '400', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(350, 'Nortriptyline', '25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(351, 'Nystatin', '100000', 'unit/1 mL', null, 'suspension', 'oral', null, null, false, null, false),
(352, 'Octreotide', '100', 'mcg/1 mL', null, 'vial', 'IV', null, null, false, null, false),
(355, 'Olive oil (น้ำมันมะกอก)', '100', 'mL/100 mL', null, 'oil', 'topical', null, null, false, null, false),
(357, 'Omeprazole', '20', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(358, 'Omeprazole', '40', 'mg', null, 'vial', 'IV', null, null, false, 'C', false),
(359, 'Ondansetron', '4', 'mg/2 mL', null, 'injection', 'IV', null, null, false, null, false),
(360, 'Oxybutynin', '5', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(361, 'Oxytocin', '10', 'IU/mL', null, 'injection', 'IV', null, null, false, 'X', false),
(362, 'Paracetamol', '120', 'mg/5 mL', null, 'syrup', 'oral', null, null, false, 'B', false),
(364, 'Paracetamol', '325', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(365, 'Paracetamol', '500', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(367, 'Paracetamol + Orphenadrine', '450 + 35', 'mg', null, 'tab', 'oral', null, 'Norgesic', false, 'C', false),
(368, 'Penicillin G sodium', '5', 'MU', null, 'vial', 'IV', null, null, false, 'B', false),
(370, 'Penicillin V', '250', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(372, 'Perphenazine', '4', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(373, 'Perphenazine', '8', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(374, 'Pethidine hydrochloride', '50', 'mg/mL', null, 'injection', 'IV', null, null, false, null, false),
(375, 'Phenobarbital', '60', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(376, 'Salicylic acid', '25', 'g/100 mL', null, 'solution', 'topical', null, null, false, null, false),
(377, 'Phenytoin (Infatab)', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(378, 'Phenytoin', '100', 'mg', null, 'cap', 'oral', 'IR', null, false, 'D', false),
(379, 'Phenytoin', '250', 'mg/5 mL', null, 'amp', 'IV', null, null, true, null, false),
(380, 'Phosphate', '30', 'mL', null, 'solution', 'oral', null, null, false, null, false),
(381, 'Phytomenadione (Vitamin K1)', '1', 'mg/0.5ml', null, 'injection', 'IV', null, null, false, 'C', false),
(382, 'Phytomenadione (Vitamin K1)', '10', 'mg/mL', null, 'injection', 'IV', null, null, false, 'C', false),
(383, 'Pioglitazone', '30', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(384, 'Piperacillin + Tazobactam', '4 + 0.5', 'g', null, 'injection', 'IV', null, null, false, null, true),
(385, 'Piracetam', '800', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(388, 'Potassium chloride', '6.67', 'mEq/5 mL', null, 'elixir', 'oral', null, null, false, 'A', false),
(390, 'Potassium chloride', '20', 'meq/10 mL', null, 'injection', 'IV', null, null, true, 'A', false),
(392, 'Povidone iodine', '10', 'g/100 mL', null, 'solution', 'topical', null, null, false, null, false),
(394, 'Praziquantel', '600', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(395, 'Prednisolone', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(396, 'Prednisolone', '0.5', 'g/100 g', '0.5', 'cream', 'topical', null, null, false, null, false),
(397, 'Primaquine', '15', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(398, 'Propranolol', '10', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(399, 'Propylthiouracil', '50', 'mg', null, 'tab', 'oral', null, null, false, 'D', false),
(400, 'Protionamide', '250', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(401, 'Pseudoephedrine', '60', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(404, 'Pyrazinamide', '500', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(405, 'Pyridoxine (Vitamin B6)', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(407, 'Quetiapine', '25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(408, 'Quetiapine', '200', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(409, 'Quinine dihydrochloride', '600', 'mg/2 mL', null, 'injection', 'IV', null, null, false, 'X', false),
(414, 'Remdesivir', '100', 'mg', null, 'injection', 'IV', null, null, false, null, false),
(415, 'Ribavirin', '200', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(417, 'Rifampicin', '300', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(418, 'Rifampicin', '450', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(419, 'Rifapentine', '150', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(420, 'Rilpivirine', '25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(421, 'Risperidone', '1', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(422, 'Risperidone', '1', 'mg/mL', null, 'syrup', 'oral', null, null, false, null, false),
(423, 'Risperidone', '2', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(424, 'Ritonavir', '100', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(426, 'Roxithromycin', '150', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(427, 'Salbutamol', '100', 'mcg/1 dose', null, 'MDI', 'inhaled', null, null, false, null, false),
(428, 'Salbutamol', '500', 'mg/100 mL', null, 'nebule', 'inhaled', null, null, false, 'A', false),
(429, 'Salbutamol', '500', 'mg/100 mL', null, 'solution', null, null, null, false, null, false),
(430, 'Senna glycosides', '7.5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(431, 'Sertraline', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(432, 'Sildenafil', '20', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(433, 'Sildenafil', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(434, 'Silver sulfadiazine', '1', 'g/100 g', '1', 'cream', 'topical', null, null, false, 'B', false),
(435, 'Simethicone', '40', 'mg/0.6ml', null, 'drops', null, null, null, false, null, false),
(436, 'Simethicone', '80', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(438, 'Simvastatin', '40', 'mg', null, 'tab', 'oral', null, null, false, 'X', false),
(439, 'Sodium bicarbonate', '7.5', 'g/100 mL', null, 'amp', 'IV', null, null, false, 'C', false),
(441, 'Sodium bicarbonate', '300', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(442, 'Sodium bicarbonate (หยอดหู)', null, null, '3', 'solution', 'topical', null, null, false, null, false),
(443, 'Sodium valproate', '200', 'mg', null, 'tab', 'oral', 'IR', null, false, 'D', false),
(444, 'Sodium valproate', '200', 'mg', null, 'tab', 'oral', 'ER', 'Depakine Chrono', false, 'D', false),
(445, 'Sodium valproate', '200', 'mg/mL', null, 'syrup', 'oral', null, null, false, null, false),
(446, 'Sodium valproate', '500', 'mg', null, 'tab', 'oral', 'ER', 'Depakine Chrono', false, 'D', false),
(447, 'Spironolactone', '25', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(448, 'Stavudine', '20', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(449, 'Stavudine', '30', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(450, 'Stavudine', '40', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(451, 'Streptokinase', '1.5', 'MU', null, 'vial', 'IV', null, null, false, null, false),
(452, 'Streptomycin', '1', 'g', null, 'injection', 'IV', null, null, false, 'D', false),
(453, 'Trimethoprim Sulfamethoxazole (Co-trimoxazole)', '40 + 200', 'mg/5 mL', null, 'suspension', 'oral', null, null, false, 'C', true),
(454, 'Trimethoprim Sulfamethoxazole (Co-trimoxazole)', '80 + 400', 'mg', null, 'injection', 'IV', null, null, false, 'C', true),
(455, 'Trimethoprim Sulfamethoxazole (Co-trimoxazole)', '80 + 400', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(456, 'Trimethoprim Sulfamethoxazole (Co-trimoxazole)', '160 + 800', 'mg', null, 'tab', 'oral', null, null, false, 'C', true),
(457, 'Sulfasalazine', '500', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(458, 'Tamoxifen', '20', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(459, 'Tenofovir alafenamide', '25', 'mg', null, 'tab', 'oral', null, null, false, 'B', false),
(460, 'Tenofovir alafenamide +  Emtricitabine + Dolutegravir', '25 + 200 + 50', 'mg', null, 'tab', 'oral', null, 'KOCITAF', false, null, false),
(461, 'Tenofovir disoproxil fumarate', '300', 'mg', null, 'tab', 'oral', null, null, false, 'B', true),
(462, 'Tenofovir disoproxil fumarate + Efavirenz + Emtricitabine', '300 + 600 + 200', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(463, 'Tenofovir disoproxil fumarate + Emtricitabine', '300 + 200', 'mg', null, 'tab', 'oral', null, null, false, null, true),
(464, 'Tenofovir disoproxil fumarate + Lamivudine + Dolutegravir', '300 + 300 + 50', 'mg', null, 'tab', 'oral', null, 'TLD', false, null, true),
(465, 'Terbutaline', '0.5', 'mg/mL', null, 'injection', 'IV', null, null, false, 'B', false),
(466, 'Terbutaline', '1.5', 'mg/5 mL', null, 'syrup', 'oral', null, null, false, null, false),
(470, 'Thc cannabis oil', '13', 'mg/mL', null, 'oil', 'oral', null, null, false, null, false),
(471, 'Theophylline', '200', 'mg', null, 'cap', 'oral', 'SR', null, false, 'C', false),
(472, 'Thioridazine', '25', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(473, 'Thioridazine', '50', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(474, 'Ticlopidine', '250', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(475, 'Topiramate', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(476, 'Tramadol', '50', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(477, 'Tramadol', '50', 'mg/mL', null, 'injection', 'IV', null, null, false, 'C', false),
(478, 'Tranexamic acid', '250', 'mg', null, 'cap', 'oral', null, null, false, null, false),
(479, 'Tranexamic acid', '250', 'mg/5 mL', null, 'injection', 'IV', null, null, false, null, false),
(480, 'Trazodone', '50', 'mg', null, 'tab', 'oral', null, null, false, null, false),
(481, 'Triamcinolone acetonide', '10', 'mg/mL', null, 'injection', 'IV', null, null, false, 'C', false),
(482, 'Triamcinolone acetonide', '20', 'mg/100 g', '0.02', 'cream', 'topical', null, null, false, null, false),
(483, 'Triamcinolone acetonide', '40', 'mg/mL', null, 'injection', 'IV', null, null, false, null, false),
(484, 'Triamcinolone acetonide', '100', 'mg/100 g', '0.1', 'cream', 'topical', null, null, false, null, false),
(485, 'Triamcinolone acetonide', '100', 'mg/100 g', '0.1', 'paste', 'topical', null, null, false, null, false),
(486, 'Trifluoperazine', '5', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(488, 'Umeclidinium + Vilanterol', '62.5 + 25', 'mcg', null, 'inhaler', 'inhaled', null, 'Anoro', false, null, false),
(490, 'Vancomycin', '500', 'mg', null, 'vial', 'IV', null, null, false, 'C', true),
(491, 'Vaseline', null, null, null, 'ointment', 'topical', null, null, false, null, false),
(492, 'Verapamil', '40', 'mg', null, 'tab', 'oral', null, null, false, 'C', false),
(495, 'Warfarin', '2', 'mg', null, 'tab', 'oral', null, null, true, 'X', false),
(496, 'Warfarin', '3', 'mg', null, 'tab', 'oral', null, null, true, 'X', false),
(497, 'Warfarin', '5', 'mg', null, 'tab', 'oral', null, null, true, 'X', false),
(499, 'Zidovudine', '10', 'mg/1 mL', null, 'syrup', 'oral', null, null, false, 'C', false),
(500, 'Zidovudine', '100', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(501, 'Zidovudine', '300', 'mg', null, 'cap', 'oral', null, null, false, 'C', false),
(502, 'Zinc oxide', '7.5', 'g/100 g', '7.5', 'paste', 'topical', null, null, false, null, false),
(503, 'ขี้ผึ้งไพล', '20', '%', null, 'ointment', 'topical', null, null, false, null, false),
(505, 'แก้ไอผสมมะขามป้อม สูตรตำรับที่ 1', '10', '%', null, 'solution', 'oral', null, null, false, null, false),
(508, 'มะขามแขก', null, null, null, 'cap', 'oral', null, null, false, null, false)
on conflict (id) do nothing;
