-- 0009: เปิดให้แก้ไขคลังยา (drugs) จากเว็บได้ + ทำ id ให้ auto-generate
-- เหตุผล: v0.9.10.0 เพิ่มหน้า "คลังยา" ให้ค้น/กรอง/เพิ่ม/แก้/ลบ/ส่งออกได้จากเว็บ (เขียนเข้า Supabase ตรง)
--         เดิม RLS ของ drugs อ่านได้อย่างเดียว + id เป็น integer ที่ seed มือ (เพิ่มยาใหม่จะ id ชน)
-- โมเดลความปลอดภัย: เปิด write ให้ anon/authenticated เหมือนตาราง incidents (แอปนี้ไม่มี auth · คุมด้วยความลับของ URL)

-- 1) id auto: ทำคอลัมน์ id เป็น identity (BY DEFAULT = ใส่ค่าเองก็ได้ / ไม่ใส่ก็ auto)
alter table public.drugs alter column id add generated by default as identity;
-- ดัน sequence ให้เริ่มเหนือ id สูงสุดปัจจุบัน (กันชนกับที่ seed ไว้)
select setval(pg_get_serial_sequence('public.drugs', 'id'), coalesce((select max(id) from public.drugs), 1));

-- 2) RLS: เปิด insert / update / delete (เดิมมีแค่ "drugs read" = select)
drop policy if exists "drugs insert" on public.drugs;
create policy "drugs insert" on public.drugs for insert to anon, authenticated with check (true);

drop policy if exists "drugs update" on public.drugs;
create policy "drugs update" on public.drugs for update to anon, authenticated using (true) with check (true);

drop policy if exists "drugs delete" on public.drugs;
create policy "drugs delete" on public.drugs for delete to anon, authenticated using (true);
