-- 0010: ประวัติการแก้ไขคลังยา (audit log) + ล็อกไม่ให้ลบยาจากเว็บ
-- เหตุผล: พี่กันอยากรู้ว่ามีใครแก้/เปลี่ยนชื่อยาตอนไหน (กันแอบเปลี่ยน) + ดูประวัติเปลี่ยนชื่อได้
--         · ลบยาให้ทำผ่าน Supabase เท่านั้น (พี่กันคนเดียว) → ถอน RLS delete ของ anon ออก
-- trigger จับ "ทุกการเปลี่ยน" ไม่ว่าจะมาจากเว็บ / Supabase dashboard / MCP → เชื่อถือได้

-- ตารางเก็บ log
create table if not exists public.drug_audit (
  id         bigint generated by default as identity primary key,
  drug_id    integer,
  action     text not null,            -- INSERT / UPDATE / DELETE
  changed_at timestamptz not null default now(),
  old_data   jsonb,                    -- แถวก่อนแก้ (UPDATE/DELETE)
  new_data   jsonb                     -- แถวหลังแก้ (INSERT/UPDATE)
);
create index if not exists drug_audit_drug_idx on public.drug_audit (drug_id, changed_at desc);

-- ฟังก์ชัน trigger — SECURITY DEFINER เพื่อให้เขียน log ได้แม้ผู้เรียกไม่มีสิทธิ์เขียนตาราง audit
create or replace function public.log_drug_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'DELETE') then
    insert into public.drug_audit(drug_id, action, old_data) values (old.id, 'DELETE', to_jsonb(old));
    return old;
  elsif (tg_op = 'UPDATE') then
    insert into public.drug_audit(drug_id, action, old_data, new_data) values (new.id, 'UPDATE', to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.drug_audit(drug_id, action, new_data) values (new.id, 'INSERT', to_jsonb(new));
    return new;
  end if;
end;
$$;

drop trigger if exists drugs_audit on public.drugs;
create trigger drugs_audit after insert or update or delete on public.drugs
  for each row execute function public.log_drug_change();

-- RLS: อ่าน log ได้ (เอาไปโชว์ประวัติ) · ห้าม anon เขียน/แก้/ลบ log (มีแต่ trigger เขียนผ่าน SECURITY DEFINER)
alter table public.drug_audit enable row level security;
drop policy if exists "drug_audit read" on public.drug_audit;
create policy "drug_audit read" on public.drug_audit for select to anon, authenticated using (true);

-- ล็อกลบยาจากเว็บ: ถอน policy delete ของ anon (เพิ่มใน 0009) → ลบได้เฉพาะผ่าน Supabase (service_role bypass RLS)
drop policy if exists "drugs delete" on public.drugs;
